### ISSUE TITLE
Lite plan limitations 

### ISSUE THREAD

**Issue by jandre1** [IBM-Bluemix-Docs/compare-comply#43]
Please, is the Lite plan capable of submitting method _POST /v1/html_conversion?_ I'm trying that but getting the error below: 

  ```
"code" : 403,
  "error" : "You are not authorized to process this API call. Unauthorized action: (method: 'POST')"
```

Thanks, João.

**Comment by scot-taylor-ibm** [comment]
Please ask in the Slack channels #cnc-tech-questions and #cnc-officehours in the ibm-watson.slack.com workspace. Thanks.

I'm closing this because it's not a technical documentation issue.

**Comment by scot-taylor-ibm** [comment]
I believe the answer is that the `/v1/html_conversion` method is not included with the Lite plan, but please visit https://cloud.ibm.com/unifiedsupport/supportcenter for verification. Thank you.
